spring:
  application:
    name: pokemon-api

  datasource:
    url: jdbc:h2:mem:pokemon-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console

gcp:
  project-id: my-project-1472045707343
  pokemon-topic: my-pokemon-topic
